version: '3.9'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: RentACar
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Docker port- app run port
      - "8081:8080"
    depends_on:
      - postgres-db
    container_name: rent-a-car
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/RentACar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
